"""
Test the 'natural torus' hypothesis:

Hypothesis: among the 26 pieces, the pieces with T_1 = m_2345 and T_2 = m_1235
correspond to a single T^{n-1} = T^2-action on AII (the 'natural torus').

For these pieces:
- T_1, T_2 are coordinate functions on AII (not linear combos).
- The other 4 BDI vars (M_2, B_1, B_2, S) may still differ across pieces.

QUESTIONS:
Q1. For pieces with NATURAL T_1=m_2345, T_2=m_1235:
    Do they all agree on (M_2, P_1, P_2, S)?
Q2. If not, what's the obstruction?
Q3. Can we identify a CANONICAL piece (one whose kernel = a natural ideal,
    e.g., generated by the Cor 6 syzygies)?

Also: compute moment polytope of the natural T^2 on AII.
"""

import sys
sys.path.insert(0, '/home/agent/projects/code/2026-06-08-pi3-construction')

import sympy as sp
from verify_full_v7 import ALL_PI
from analyze_torus import (AII_VARS, BDI_VARS, CORE_VARS, MIN_COVER_26,
                            piece_matrix, core_matrix)


def is_natural_torus(spec):
    """Check if piece has T_1 = m_2345 (just) and T_2 = m_1235 (just)."""
    t1 = tuple(sorted(tuple(spec.get("T_1", []))))
    t2 = tuple(sorted(tuple(spec.get("T_2", []))))
    return t1 == ((1, "m_2345"),) and t2 == ((1, "m_1235"),)


def main():
    pieces = [n for n in MIN_COVER_26 if n in ALL_PI]
    natural = [n for n in pieces if is_natural_torus(ALL_PI[n])]
    print(f"Natural-torus pieces ({len(natural)} out of {len(pieces)}):")
    for n in natural:
        print(f"  {n}")

    if not natural:
        print("\nNo natural-torus pieces. Aborting.")
        return

    # Compute core for each natural piece
    print("\n--- Cores for natural-torus pieces ---")
    cores = {}
    for n in natural:
        cm = core_matrix(ALL_PI[n])
        cores[n] = cm
        print(f"\n  {n}:")
        for r, label in enumerate(CORE_VARS):
            row = cm[r, :]
            terms = []
            for j in range(9):
                c = int(row[j])
                if c != 0:
                    s = "+" if c > 0 else "-"
                    val = abs(c)
                    t = f"{s}{AII_VARS[j]}" if val == 1 else f"{s}{val}*{AII_VARS[j]}"
                    terms.append(t)
            print(f"    {label} = {' '.join(terms)}")

    # Common core kernel for natural pieces
    print("\n--- Common core kernel for natural-torus pieces ---")
    big = sp.Matrix.vstack(*[cores[n] for n in natural])
    print(f"  Stacked shape: {big.shape}, rank: {big.rank()}")
    ker = big.nullspace()
    print(f"  Common kernel dim: {len(ker)}")
    for v in ker:
        d = {AII_VARS[j]: int(v[j]) for j in range(9) if v[j] != 0}
        print(f"    ker = {d}")

    # Test ONE specific natural piece: P5a_m2_in_S
    sample = "P5a_m2_in_S"
    if sample in ALL_PI:
        print(f"\n--- Detailed analysis of {sample} ---")
        A = piece_matrix(ALL_PI[sample])
        print(f"Full BDI matrix:")
        for r, label in enumerate(BDI_VARS):
            row = [int(A[r, j]) for j in range(9)]
            print(f"  {label}: {dict(zip(AII_VARS, row))}")

        # Find directions in kernel
        ns = A.nullspace()
        print(f"\nKernel (dim {len(ns)}):")
        for i, v in enumerate(ns):
            d = {AII_VARS[j]: int(v[j]) for j in range(9) if v[j] != 0}
            print(f"  ker[{i}] = {d}")

        # Is m_23456 a kernel direction? (It should be free in AII.)
        # m_23456 vector
        e_23456 = sp.zeros(9, 1)
        e_23456[AII_VARS.index("m_23456")] = 1
        if A * e_23456 == sp.zeros(6, 1):
            print(f"\n  m_23456 IS in kernel of {sample}.")
        else:
            print(f"\n  m_23456 NOT in kernel of {sample}: image = {[int(x) for x in (A*e_23456).T.tolist()[0]]}")

    # Check: which AII vars have non-zero image in ALL 26 pieces?
    print("\n--- AII var images across all pieces ---")
    for j, av in enumerate(AII_VARS):
        zero_in = []
        nonzero_in = 0
        for n in pieces:
            A = piece_matrix(ALL_PI[n])
            if all(A[r, j] == 0 for r in range(6)):
                zero_in.append(n)
            else:
                nonzero_in += 1
        if zero_in:
            print(f"  {av}: zero in {len(zero_in)} pieces ({nonzero_in} nonzero)")
        else:
            print(f"  {av}: nonzero in all {nonzero_in} pieces")


if __name__ == "__main__":
    main()
