"""
Deeper analysis of how Aug~ relates to ψ_J:

Observation from full_comparison.py: Aug~ acts on (w, π) but at the w-level only changes
w by a simple reflection. ψ_I in W(B_2), in contrast, swaps elements in nontrivial 3-cells:
{s_1, s_0 s_1, s_1 s_0 s_1} → {s_1 s_0 s_1, s_0 s_1, s_1} (transposition of the two
end elements; middle fixed). So Aug~ at the w-level is structurally DIFFERENT from ψ_I.

Key question: maybe Aug~ should be compared to ψ_J for *small* J like ∅ or {s_0} or {s_1},
because these are TRIVIAL involutions on W(B_2). And indeed ψ_∅ = ψ_{s_0} = ψ_{s_1} = id
on W(B_2). But Aug~ at the w-level is NOT identity (it actively moves w around).

So Aug~ is incompatible with all four ψ_J in B_2 *at the w-level*.

What might work better: compare Aug~ to GY's ψ_J on (w, π) pairs by LIFTING the parabolic
decomposition to root level. I.e., decompose π by the parabolic structure too. But GY don't
do this — there's no Kostant-partition structure in their construction.

Alternative compelling idea: Maybe Aug~ is a "BOTTOM-UP" sign-reversing involution
constructed from the data of (λ, μ) — and ψ_J is a "TOP-DOWN" basis-level involution.
They could implement the same KL-positivity result but through totally different combinatorics.

Test: Compare the SET of fixed points (= even-length contributing items):
  Aug~: even-length (w, π) such that no move applies.
  ψ_J: w fixed by ψ_J iff Mathas's involution fixes Res_J(x). For J = full I, the fixed
       points of ψ_I are {e, s_0 s_1, s_1 s_0, s_0 s_1 s_0 s_1} (even-length elements).
"""
import sys
sys.path.insert(0, '/home/agent/projects/proofs/remark47')
sys.path.insert(0, '/home/agent/projects/proofs/remark47/route_B')

from fractions import Fraction
from collections import defaultdict
from aug_tilde_B2 import (
    weyl_B2, w_label_to_func,
    all_kostant_partitions_B2, bidegree_of_partition,
    apply_aug_tilde, RHO_B2,
)
from kl_W_B2 import length, reduced_word
from psi_J_B2 import compute_psi_J


def name_w(label):
    rw = reduced_word(label)
    return "e" if not rw else "".join(f"s{i}" for i in rw)


def aug_fixed_points(lam, mu):
    """Return the set of w-labels that have at least one π for which (w, π) is Aug~-fixed."""
    tilde_a = tuple(int(lam[i] + RHO_B2[i]) for i in range(2))
    b = tuple(int(mu[i] + RHO_B2[i]) for i in range(2))
    weyl = weyl_B2()
    fixed_w = set()
    all_w = set()
    for w_func, length_, label in weyl:
        wa = w_func(tilde_a)
        beta_w = tuple(wa[i] - b[i] for i in range(2))
        if beta_w[0] < 0:
            continue
        pis = all_kostant_partitions_B2(beta_w)
        for pi in pis:
            all_w.add(label)
            result, _ = apply_aug_tilde(label, pi, tilde_a)
            if result is None:
                fixed_w.add(label)
    return fixed_w, all_w


def main():
    F = Fraction
    half = F(1, 2)

    # Get psi_I fixed-point set
    psi_I, _ = compute_psi_J((0, 1))
    psi_I_fixed = set(w for w in psi_I if psi_I[w] == w)

    print(f"ψ_I fixed-point set in W(B_2): {sorted([name_w(w) for w in psi_I_fixed])}")
    print(f"  (This is the *even-length elements* — coincidence with Aug~ structure?)")

    # Test on all dominant spin pairs
    test_pairs = []
    for l1 in range(5):
        for l2 in range(l1 + 1):
            lam = (l1 + half, l2 + half)
            for m1 in range(l1 + 1):
                for m2 in range(m1 + 1):
                    mu = (m1 + half, m2 + half)
                    test_pairs.append((lam, mu))

    # Question: is Aug~'s fixed-point set in w \subseteq ψ_I fixed-point set?
    discrepancies = []
    for lam, mu in test_pairs:
        aug_fixed, aug_all = aug_fixed_points(lam, mu)
        # Check inclusion
        contained_in_psi_I_fixed = aug_fixed.issubset(psi_I_fixed)
        if not contained_in_psi_I_fixed:
            discrepancies.append((lam, mu, aug_fixed - psi_I_fixed))

    print(f"\n=== Question 1: Does Aug~-fixed (at the w-level) ⊆ ψ_I-fixed? ===")
    print(f"  Yes for {len(test_pairs) - len(discrepancies)}/{len(test_pairs)} pairs")
    if discrepancies:
        print(f"  Discrepancies:")
        for lam, mu, extra in discrepancies[:5]:
            print(f"    λ={lam}, μ={mu}: extra = {[name_w(w) for w in extra]}")

    # Question 2: Does Aug~ project to ψ_I as cosets? I.e., does Aug~ act trivially on
    # the QUOTIENT W / (the equivalence relation generated by ψ_I)?
    # Equivalently: does Aug~(w) lie in the ψ_I-orbit of w for all (w, π)?
    psi_I_orbits = defaultdict(set)
    for w in psi_I:
        psi_I_orbits[w].add(w)
        psi_I_orbits[w].add(psi_I[w])
    # Each orbit: {w, ψ_I(w)}
    orbit_of = {}
    for w in psi_I:
        orbit_of[w] = frozenset([w, psi_I[w]])

    print(f"\n=== Question 2: Does Aug~(w, π)'s w stay in ψ_I-orbit of w? ===")
    cnt_in_orbit = 0
    cnt_total = 0
    examples = []
    for lam, mu in test_pairs:
        tilde_a = tuple(int(lam[i] + RHO_B2[i]) for i in range(2))
        b = tuple(int(mu[i] + RHO_B2[i]) for i in range(2))
        weyl = weyl_B2()
        for w_func, length_, label in weyl:
            wa = w_func(tilde_a)
            beta_w = tuple(wa[i] - b[i] for i in range(2))
            if beta_w[0] < 0:
                continue
            pis = all_kostant_partitions_B2(beta_w)
            for pi in pis:
                cnt_total += 1
                result, move = apply_aug_tilde(label, pi, tilde_a)
                if result is None:
                    target = label
                else:
                    target = result[0]
                if target in orbit_of[label]:
                    cnt_in_orbit += 1
                else:
                    if len(examples) < 5:
                        examples.append((lam, mu, label, pi, target, move))
    print(f"  In-orbit: {cnt_in_orbit}/{cnt_total} ({100*cnt_in_orbit/cnt_total:.1f}%)")
    if examples:
        print(f"  Out-of-orbit examples:")
        for lam, mu, w, pi, target, move in examples:
            pi_str = "{" + ",".join(f"{r}:{c}" for r, c in sorted(pi.items())) + "}"
            print(f"    λ={lam}, μ={mu}: w={name_w(w)}, π={pi_str} → {name_w(target)} ({move}); ψ_I-orbit of w = {[name_w(x) for x in orbit_of[w]]}")


if __name__ == "__main__":
    main()
