"""
Compute ψ_J : W(B_2) → W(B_2) for each subset J ⊆ I = {0, 1}, per Definition B.7
of Gossow-Yacobi 2023.

Recipe:
  1. Choose J ⊆ I with W_J finite (always true for finite W).
  2. For x ∈ W, decompose x = u · a with u ∈ W_J and a = π_J(x) the minimal-length
     element of W_J · x. Set Res_J(x) := u.
  3. ψ_J(x) := ψ_{C(u)}(u) · a, where C(u) is the left cell of W_J containing u and
     ψ_{C(u)} is Mathas's involution on that cell.

Subsets to consider for B_2:
  J = ∅:    W_J = {e}, ψ_J = identity.
  J = {0}:  W_J = {e, s_0} ≅ W(A_1). Left cells: each singleton (since A_1 has 2 cells).
            Mathas ψ_C on each: identity (singleton cells).
  J = {1}:  W_J = {e, s_1} ≅ W(A_1). Same.
  J = I = {0, 1}: W_J = W(B_2), ψ_J = ψ_I (computed in mathas_involution_B2.py).

Wait — for A_1 = {e, s}, the left cells under W = A_1 are:
  Cell {e}: w_I = s, s · C_e = s · e = s = C_s - C_e... so s · C_e = C_s - C_e.
  In V({e}) = C[W]^≤ / C[W]^< -- but since {e} is below {s}, V({e}) is 1-dim, and
  the action of s is by -1 (the sign rep restricted).
  Actually for Sn the cells are all singletons -- cells of A_1 are {e} and {s}.
  ψ on each is identity.

Hmm but A_1 has 2 left cells: {e} and {s}? Let me verify.
For W = A_1: KL polys are all 1. Left preorder: e <-1- s gives e ≤_L s. Is s ≤_L e? No,
because s_1 e = s_1 has s_1 in left descent? No -- DL(e) = ∅, so s_1 NOT in DL(e),
so action s_1 · C_e = C_{s_1} + ... so s ≤_L e. So e ~_L s? Let me check both directions:
  s_1 · C_e: s_1 ∉ DL(e). C_e = e (group ring). So s_1 · C_e = s_1 = C_{s_1} - C_e... no:
  C_{s_1} = e + s_1, so C_e + C_{s_1} = 2e + s_1, so s_1 = C_{s_1} - C_e.
  Hmm, so s_1 · C_e = C_{s_1} - C_e. So C_{s_1} appears with coeff +1, hence s ≤_L e.
And what is s_1 · C_{s_1}? C_{s_1} = e + s_1 = e + s_1. Then s_1 · C_{s_1} = s_1 + e = C_{s_1}.
So the only KL element appearing in s_1 · C_{s_1} is C_{s_1} itself. No new x's. So ≤_L not generated.

What about s_1 ≤_L e? We computed s ≤_L e. What about e ≤_L s? In s_1 · C_{s_1} = C_{s_1},
no C_e appears (well, expand: C_{s_1} = e + s_1; so C_e doesn't appear). Hmm.
But s_1 ∈ DL(s_1), so by the rule "if s_i ∈ DL(y), no new x's appear" — we don't get e <- s.
So e and s are in DIFFERENT left cells.

Wait, but s ≤_L e (since s ∈ s_1 · C_e). And we just argued e is not ≤_L s. So:
   Cell of e: contains s? Only if e ~_L s, i.e., both directions. s ≤_L e but e not ≤_L s.
   So cells: {e} and {s} — yes, 2 singleton cells in A_1.

Mathas on singleton cells: ψ_C = identity (only one element).

So ψ_{J} for J = {0} or {1} acts trivially on the W_J component. But it still permutes
elements via Res_J(x) being identity vs. s. Wait — ψ_J(x) = ψ_C(Res_J(x)) · π_J(x). If
ψ_C = id on each cell, then ψ_J(x) = Res_J(x) · π_J(x) = x. So ψ_J = id when J = {0} or {1}.

So for B_2 the only NONTRIVIAL ψ_J is ψ_I (J = full diagram).

Hmm — that gives a much shorter answer. Let me re-examine. What about J = ∅? W_∅ = {e},
trivial. ψ_∅ = id.

So in B_2, ψ_J is identity for J ∈ {∅, {0}, {1}}, and only nontrivial for J = I.
"""

from kl_W_B2 import (
    all_elements_B2, length, multiply, ID, S0, S1,
    bruhat_le, kl_polynomial_table, left_preorder_relations,
    compute_left_cells, reduced_word, transitive_closure
)
from mathas_involution_B2 import (
    name_elements, gr_zero, gr_singleton, gr_add, gr_sub, gr_left_mul,
    C_basis_element, expand_in_KL, w_longest_B2,
    compute_mathas_involution_B2,
)


# Build W_J as a subset of W(B_2)
def W_J(J):
    """Return list of elements of W(B_2) generated by {s_i | i ∈ J}."""
    gens = []
    for i in J:
        gens.append([S0, S1][i])
    out = [ID]
    seen = {ID}
    if not gens:
        return out
    changed = True
    while changed:
        changed = False
        for w in list(out):
            for g in gens:
                wg = multiply(w, g)
                if wg not in seen:
                    seen.add(wg)
                    out.append(wg)
                    changed = True
    return out


def parabolic_decomposition(x, J):
    """Decompose x = u · a with u ∈ W_J and a = min-length element of W_J · x.

    Equivalently, x = u · a iff a = u^{-1} · x. Among all u ∈ W_J, find the one
    that makes a have minimal length. Then a is the unique minimal coset rep in W_J \ W
    for the right coset W_J · x.
    """
    wJ = W_J(J)
    best_a = None
    best_u = None
    best_len = None
    for u in wJ:
        # a = u^{-1} · x; for involution u (since W_J generated by reflections, but in general not),
        # for now just compute u^{-1} via matrix inverse: u is signed permutation, u^{-1}
        # has perm = inverse perm and signs adjusted.
        u_inv = inverse(u)
        a = multiply(u_inv, x)
        la = length(a)
        if best_len is None or la < best_len:
            best_len = la
            best_a = a
            best_u = u
    return best_u, best_a


def inverse(w):
    """Inverse of signed permutation w = (pi, signs): pi'[pi[i]] = i, signs'[pi[i]] = signs[i]."""
    pi, signs = w
    new_pi = [0, 0]
    new_signs = [1, 1]
    for i in range(2):
        new_pi[pi[i]] = i
        new_signs[pi[i]] = signs[i]
    return (tuple(new_pi), tuple(new_signs))


def left_cells_of_subgroup(elements_subgroup):
    """Compute left cells of the subgroup W_J considered as its own Coxeter group.

    Since we only care about W_J for J ⊆ {0,1} of size ≤ 2, and for size = 0, 1, 2
    things are easy:
      |J| = 0: W_J = {e}, single cell.
      |J| = 1: W_J = {e, s_i} ≅ A_1, two singleton cells {e} and {s_i}.
      |J| = 2: W_J = full W(B_2), 4 cells (computed before).
    """
    # We can reuse compute_left_cells, but on the subgroup ONLY. For singletons or A_1
    # this is trivial.
    # For now just handle the cases.
    if len(elements_subgroup) == 1:
        return [frozenset(elements_subgroup)]
    if len(elements_subgroup) == 2:
        # A_1: cells are {e}, {s}
        return [frozenset([w]) for w in elements_subgroup]
    # otherwise full W(B_2)
    elts_sorted = sorted(elements_subgroup, key=lambda w: (length(w), w))
    P = kl_polynomial_table(elts_sorted)
    return compute_left_cells(elts_sorted, P)


_PSI_FULL_CACHE = None
def _get_psi_full():
    global _PSI_FULL_CACHE
    if _PSI_FULL_CACHE is None:
        # Suppress prints during computation
        import io, contextlib
        f = io.StringIO()
        with contextlib.redirect_stdout(f):
            _, _, psi_full, _, _, _ = compute_mathas_involution_B2()
        _PSI_FULL_CACHE = psi_full
    return _PSI_FULL_CACHE


def compute_psi_J(J):
    """Compute ψ_J : W(B_2) → W(B_2)."""
    elements = all_elements_B2()
    elements_sorted = sorted(elements, key=lambda w: (length(w), w))
    name = name_elements(elements_sorted)

    wJ_elements = W_J(J)
    cells_J = left_cells_of_subgroup(wJ_elements)

    # Compute ψ_C on each cell of W_J. For size-1 or size-2 cells in subgroups of W(B_2),
    # cells are singletons → ψ_C = id.
    # For W_J = full W(B_2), use compute_mathas_involution_B2.
    psi_C_subgroup = {}  # u ∈ W_J -> ψ_C(u)
    if len(wJ_elements) <= 2:
        for u in wJ_elements:
            psi_C_subgroup[u] = u
    else:
        # Full W(B_2)
        psi_full = _get_psi_full()
        for u in wJ_elements:
            psi_C_subgroup[u] = psi_full[u]

    psi_J_map = {}
    for x in elements_sorted:
        u, a = parabolic_decomposition(x, J)
        u_psi = psi_C_subgroup[u]
        psi_x = multiply(u_psi, a)
        psi_J_map[x] = psi_x

    return psi_J_map, name


def main():
    elements = all_elements_B2()
    elements_sorted = sorted(elements, key=lambda w: (length(w), w))
    name = name_elements(elements_sorted)

    print("=== ψ_J : W(B_2) → W(B_2) for each J ⊆ {0, 1} ===\n")

    for J in [(), (0,), (1,), (0, 1)]:
        psi_J_map, _ = compute_psi_J(J)
        print(f"\n--- J = {J} (W_J = {[name[w] for w in W_J(J)]}) ---")
        for x in elements_sorted:
            u, a = parabolic_decomposition(x, J)
            print(f"  x = {name[x]:<10s}: u = {name[u]:<10s}, a = π_J(x) = {name[a]:<10s},  ψ_J(x) = {name[psi_J_map[x]]}")
        # Verify involution
        for x in elements_sorted:
            assert psi_J_map[psi_J_map[x]] == x, f"NOT an involution: J={J}, x={name[x]}"
        print(f"  ✓ Involution.")


if __name__ == "__main__":
    main()
