"""
BGG vs Aug~ comparison for F_4.

Mirrors bgg_aug_compare_C3.py with an orbit-based move representation suitable
for the more complex F_4 root system.

Test set: dominant integer (lambda, mu) with lam - mu in root lattice (F_4 root
lattice = Z^4 since all coords of long roots are integer; the short halves have
half-integer coords but appear in groups summing to integer). Actually F_4 root
lattice = Z^4 generated by long roots PLUS the half-integer short roots
(1/2)(e_0 +- e_1 +- e_2 +- e_3); generating set is (e_i - e_j, (1/2)(e_0 - e_1 -
e_2 - e_3)) — the root lattice of F_4 equals D_4 lattice = {v in Z^4 :
sum v_i even} UNION {v in (1/2)Z^4 \ Z^4 : all coords half-integer of same parity},
i.e., the F_4 root lattice is the D_4 lattice extended by (1/2)(e_0 + e_1 + e_2 + e_3)?
Hmm. Let me think differently:

The root lattice Q(F_4) is generated by the simple roots
   alpha_0, alpha_1, alpha_2, alpha_3.
Computing: alpha_0 = (0,1,-1,0), alpha_1 = (0,0,1,-1), alpha_2 = (0,0,0,1),
alpha_3 = (1/2)(1,-1,-1,-1).

So Q(F_4) contains alpha_2 = e_3 (integer), e_3 - e_4 = alpha_1 -> e_2 = alpha_1 + alpha_2,
e_1 = alpha_0 + alpha_1 + alpha_2 = (0,1,0,0), e_0 = ??? alpha_3 = (1/2)(1,-1,-1,-1)
so 2 alpha_3 = (1,-1,-1,-1). alpha_3 + alpha_0 + alpha_1 + alpha_2 = ?
alpha_3 + e_1 = (1/2)(1,-1,-1,-1) + (0,1,0,0) = (1/2)(1,1,-1,-1). Hmm.
2*alpha_3 + 2*alpha_2 + 2*alpha_1 + 2*alpha_0 = (1,-1,-1,-1) + (0,2,-2,0) + (0,0,2,-2) + (0,0,0,2)
= (1,1,-1,-1). Not e_0.

Actually Q(F_4) is non-trivial: it contains all of Z^4 because integer roots include
e_i and e_i-e_j. So in fact Q(F_4) ⊇ Z^4. And Q(F_4) contains alpha_3 = (1/2)(1,-1,-1,-1).
Does that put us in (1/2)Z^4? Yes. Is Q(F_4) = whole (1/2)Z^4? Let's see — we have all
(1/2)(s_0, s_1, s_2, s_3) with s_i = +/- 1 by reflecting alpha_3 with s_i (since these are
roots). We have e_i. So Q(F_4) contains e_0 + alpha_3 = (3/2,-1/2,-1/2,-1/2). And e_0,
alpha_3, e_1, e_2, e_3 generate a Z-lattice containing (1/2)(1,-1,-1,-1), and Z^4,
i.e. = Z^4 + Z*(1/2)(1,-1,-1,-1). This is a Z-lattice of index 2 in (1/2)Z^4. Specifically:
v in Z^4 + Z*(1/2)(1,-1,-1,-1) iff (2v) in Z^4 AND (2v_0 - 2v_1 - 2v_2 - 2v_3) is even
(more precisely the "twist by half" parity).

Equivalently: Q(F_4) = {v in (1/2)Z^4 : v in Z^4 OR (v - (1/2)(1,-1,-1,-1)) in Z^4}.
Equivalently in terms of integer doubled: u = 2v in Z^4, with the constraint that
either u in 2Z^4 (i.e., v integer) or u-(1,-1,-1,-1) in 2Z^4 (i.e., all u-coords odd).

Net: lambda - mu must be in Q(F_4). For lam, mu both INTEGER, lambda - mu is in Z^4,
which IS contained in Q(F_4). So integer lam-mu is always OK.

Test plan:
  Very small scope:
    lam in { (0,0,0,0), (1,0,0,0), (1,1,0,0), (1,1,1,0), (1,1,1,1), (2,0,0,0),
             (2,1,0,0), (2,1,1,0), (2,2,0,0), (2,1,1,1) }
    mu dominant integer with mu_i <= lam_i, lam-mu in Z^4 (auto).
  Goal: verify (A) and (B') on each. Report stats.
"""

import os
import sys
import time
from fractions import Fraction
from collections import defaultdict, Counter
from itertools import product

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import aug_tilde_F4 as F4


def freeze_pi(pi):
    return frozenset(pi.items())


def build_basis_and_edges(lam, mu, weyl, orbit_data, pure_only=False, verbose=False):
    """Return (items, item_index, odd_idxs, edges_per_odd, tilde_a) for (lam, mu)."""
    tilde_a, b, items = F4.collect_items(lam, mu, weyl=weyl)
    item_index = {(_freeze_w(w), freeze_pi(pi)): idx for idx, (w, _, pi, _) in enumerate(items)}
    odd_idxs = [idx for idx, (_, lng, _, _) in enumerate(items) if lng % 2 == 1]
    edges = {}
    simples = F4.F4_simple_roots()
    for idx in odd_idxs:
        w, length, pi, bd = items[idx]
        w_tilde_a = F4.apply_w(w, tilde_a)
        if pure_only:
            moves = F4.list_pure_moves(w, pi, w_tilde_a, orbit_data, simples)
        else:
            moves = F4.list_all_simple_moves(w, pi, w_tilde_a, orbit_data, simples)
        ed = []
        for move_info, (new_w, new_pi) in moves:
            key = (_freeze_w(new_w), freeze_pi(new_pi))
            tgt = item_index.get(key)
            if tgt is None:
                continue
            if items[tgt][1] % 2 != 0:
                continue
            if items[tgt][3] != bd:
                continue
            ed.append((move_info, tgt))
        edges[idx] = ed
    return items, item_index, odd_idxs, edges, tilde_a


def _freeze_w(w):
    """w is a tuple of 4 4-tuples of Fractions. It is already hashable."""
    return w


def maximum_bipartite_matching(odd_idxs, edges):
    pair_odd = {}
    pair_even = {}

    def try_aug(o, visited):
        for move_info, ev in edges.get(o, []):
            if ev in visited:
                continue
            visited.add(ev)
            if ev not in pair_even or try_aug(pair_even[ev], visited):
                pair_odd[o] = (ev, move_info)
                pair_even[ev] = o
                return True
        return False

    for o in odd_idxs:
        try_aug(o, set())
    return pair_odd, pair_even


def match_pure_then_mixed(lam, mu, weyl, orbit_data, verbose=False):
    items, item_index, odd_idxs, pure_edges, tilde_a = build_basis_and_edges(
        lam, mu, weyl, orbit_data, pure_only=True, verbose=verbose)
    pair_odd_pure, pair_even_pure = maximum_bipartite_matching(odd_idxs, pure_edges)

    _, _, _, all_edges, _ = build_basis_and_edges(
        lam, mu, weyl, orbit_data, pure_only=False, verbose=verbose)

    pair_odd = dict(pair_odd_pure)
    pair_even = dict(pair_even_pure)

    def try_aug_mixed(o, visited):
        for move_info, ev in all_edges.get(o, []):
            if ev in visited:
                continue
            visited.add(ev)
            if ev not in pair_even:
                pair_odd[o] = (ev, move_info)
                pair_even[ev] = o
                return True
            else:
                occupant = pair_even[ev]
                if try_aug_mixed(occupant, visited):
                    pair_odd[o] = (ev, move_info)
                    pair_even[ev] = o
                    return True
        return False

    for o in odd_idxs:
        if o not in pair_odd:
            try_aug_mixed(o, set())

    unmatched = [o for o in odd_idxs if o not in pair_odd]
    return items, pair_odd_pure, pair_odd, unmatched, tilde_a


def classify_move(move_info, items, o_idx, e_idx):
    """Classify a matched pair.
    move_info = (simple_idx, distribution)  where distribution = {(orbit_tag, sign): count}.

    (A): does w_e = s_{si} * w_o ?
    (B'): is distribution within ONE simple_idx (by construction yes).
    """
    si, distribution = move_info
    w_o, _, pi_o, _ = items[o_idx]
    w_e, _, pi_e, _ = items[e_idx]
    expected = F4.left_mult_simple(w_o, si)
    label_check = (expected == w_e)
    all_roots = set(pi_o.keys()) | set(pi_e.keys())
    pi_diff = {}
    for r in all_roots:
        d = pi_e.get(r, 0) - pi_o.get(r, 0)
        if d != 0:
            pi_diff[r] = d
    return {
        'si': si,
        'n_orbits': len(distribution),
        'distribution': distribution,
        'label_check': label_check,
        'pi_diff': pi_diff,
    }


def per_bd_signed_sums(items):
    bd_e = Counter()
    bd_o = Counter()
    for _, lng, _, bd in items:
        if lng % 2 == 0:
            bd_e[bd] += 1
        else:
            bd_o[bd] += 1
    all_bd = set(bd_e) | set(bd_o)
    return {bd: (bd_e[bd], bd_o[bd], bd_e[bd] - bd_o[bd]) for bd in all_bd}


def dominant_integer_pairs_small():
    """A small curated set of dominant integer (lambda, mu) pairs for F_4 testing.

    lambda dominant means lam_0 >= lam_1 >= lam_2 >= |lam_3|, with lam_2 >= lam_3
    when lam_3 >= 0, etc. For integer F_4 dominant chamber:
      lam in fundamental weights basis must have non-negative coefficients.
    In the e-basis: dominant chamber is lam_0 >= lam_1 >= lam_2 >= lam_3 >= 0.
    """
    F = Fraction
    pairs = []
    # Start with lam = (0,0,0,0) — trivial.
    # Then small lams:
    test_lams = [
        (0, 0, 0, 0),
        (1, 0, 0, 0),
        (1, 1, 0, 0),
        (1, 1, 1, 0),
        (1, 1, 1, 1),
    ]
    for lam_int in test_lams:
        lam = tuple(F(x) for x in lam_int)
        # mu dominant integer with mu_i <= lam_i (loose enough)
        # enumerate all (m0, m1, m2, m3) with l_i >= m_i and m_0 >= m_1 >= m_2 >= m_3 >= 0
        l0, l1, l2, l3 = lam_int
        for m0 in range(l0 + 1):
            for m1 in range(min(m0, l1) + 1):
                for m2 in range(min(m1, l2) + 1):
                    for m3 in range(min(m2, l3) + 1):
                        mu = (F(m0), F(m1), F(m2), F(m3))
                        pairs.append((lam, mu))
    return pairs


def run_test(pairs, weyl, orbit_data, verbose=True):
    grand = {
        'n_lambda_mu_pairs': 0,
        'n_basis_total': 0,
        'n_odd_total': 0,
        'n_even_total': 0,
        'n_pure_matched_total': 0,
        'n_mixed_matched_total': 0,
        'n_unmatched_odd_total': 0,
        'n_unmatched_even_total': 0,
        'n_A_ok': 0,
        'n_A_total': 0,
        'n_Bprime_ok': 0,
        'n_Bprime_total': 0,
        'orbit_use_by_si': defaultdict(Counter),
        'pure_use_by_si': defaultdict(Counter),
        'mixed_distrib_by_si': defaultdict(Counter),
        'unmatched_examples': [],
        'mixed_examples': [],
        'bgg_signed_consistency_ok': 0,
        'bgg_signed_consistency_total': 0,
        'per_lm_results': [],
    }

    t0 = time.time()
    for k_lm, (lam, mu) in enumerate(pairs):
        t_pair = time.time()
        res = match_pure_then_mixed(lam, mu, weyl, orbit_data)
        items, pair_odd_pure, pair_odd_all, unmatched, _ = res
        grand['n_lambda_mu_pairs'] += 1
        grand['n_basis_total'] += len(items)
        n_odd = sum(1 for _, lng, _, _ in items if lng % 2 == 1)
        n_even = sum(1 for _, lng, _, _ in items if lng % 2 == 0)
        grand['n_odd_total'] += n_odd
        grand['n_even_total'] += n_even
        n_pure = len(pair_odd_pure)
        n_all = len(pair_odd_all)
        n_mixed = n_all - n_pure
        n_unm_odd = len(unmatched)
        used_evens = set(ev for (ev, _) in pair_odd_all.values())
        n_unm_even = n_even - len(used_evens)
        grand['n_pure_matched_total'] += n_pure
        grand['n_mixed_matched_total'] += n_mixed
        grand['n_unmatched_odd_total'] += n_unm_odd
        grand['n_unmatched_even_total'] += n_unm_even

        per_bd = per_bd_signed_sums(items)
        unmatched_at_bd = Counter()
        for o in unmatched:
            unmatched_at_bd[items[o][3]] += 1
        unused_evens_at_bd = Counter()
        for ev_idx, (_, lng, _, bd) in enumerate(items):
            if lng % 2 != 0:
                continue
            if ev_idx not in used_evens:
                unused_evens_at_bd[bd] += 1
        for bd, (e, o, sgn) in per_bd.items():
            bgg_signed = e - o
            actual_diff = unused_evens_at_bd[bd] - unmatched_at_bd[bd]
            grand['bgg_signed_consistency_total'] += 1
            if bgg_signed == actual_diff:
                grand['bgg_signed_consistency_ok'] += 1

        for o_idx, (e_idx, move_info) in pair_odd_all.items():
            cls = classify_move(move_info, items, o_idx, e_idx)
            grand['n_A_total'] += 1
            if cls['label_check']:
                grand['n_A_ok'] += 1
            grand['n_Bprime_total'] += 1
            grand['n_Bprime_ok'] += 1  # built-in
            si = cls['si']
            if cls['n_orbits'] == 1:
                key, n_swaps = next(iter(cls['distribution'].items()))
                tag, sign = key
                # tag = ('swap', pair)
                _, pair = tag
                grand['pure_use_by_si'][si][(pair, n_swaps, sign)] += 1
            else:
                key = tuple(sorted(cls['distribution'].items()))
                grand['mixed_distrib_by_si'][si][key] += 1
                if len(grand['mixed_examples']) < 6:
                    grand['mixed_examples'].append({
                        'lam': lam, 'mu': mu,
                        'odd_w': items[o_idx][0],
                        'odd_pi': items[o_idx][2],
                        'odd_len': items[o_idx][1],
                        'even_w': items[e_idx][0],
                        'even_pi': items[e_idx][2],
                        'even_len': items[e_idx][1],
                        'si': si,
                        'distribution': cls['distribution'],
                        'pi_diff': cls['pi_diff'],
                    })

        if unmatched and len(grand['unmatched_examples']) < 4:
            for o in unmatched[:2]:
                grand['unmatched_examples'].append({
                    'lam': lam, 'mu': mu,
                    'w': items[o][0],
                    'len': items[o][1],
                    'pi': items[o][2],
                    'bd': items[o][3],
                })

        per_lm_summary = {
            'lam': lam, 'mu': mu,
            'n_items': len(items),
            'n_odd': n_odd, 'n_even': n_even,
            'n_pure': n_pure, 'n_mixed': n_mixed,
            'n_unm_odd': n_unm_odd, 'n_unm_even': n_unm_even,
            'time': time.time() - t_pair,
        }
        grand['per_lm_results'].append(per_lm_summary)

        if verbose:
            print(f"  [{k_lm+1}/{len(pairs)}] lam={lam} mu={mu}: "
                  f"items={len(items)} odd={n_odd} even={n_even} "
                  f"pure={n_pure} mixed={n_mixed} unm_o={n_unm_odd} unm_e={n_unm_even} "
                  f"({per_lm_summary['time']:.1f}s)")

    elapsed = time.time() - t0
    if verbose:
        print(f"\nTotal: {elapsed:.1f}s")
    return grand


def summarize(grand):
    print()
    print("=" * 70)
    print("BGG-Aug F_4 COMPARISON SUMMARY")
    print("=" * 70)
    print(f"# (lambda, mu) pairs processed:        {grand['n_lambda_mu_pairs']}")
    print(f"# total basis items:                   {grand['n_basis_total']}")
    print(f"# total odd-length items:              {grand['n_odd_total']}")
    print(f"# total even-length items:             {grand['n_even_total']}")
    print(f"# odd items matched by PURE moves:     {grand['n_pure_matched_total']}")
    print(f"# odd items matched by MIXED moves:    {grand['n_mixed_matched_total']}")
    print(f"# odd items UNMATCHED:                 {grand['n_unmatched_odd_total']}")
    print(f"# even items UNUSED:                   {grand['n_unmatched_even_total']}")
    print()
    if grand['n_A_total'] > 0:
        pct_A = 100.0 * grand['n_A_ok'] / grand['n_A_total']
        print(f"(A) LEFT-mult check (w' = s_i . w): "
              f"{grand['n_A_ok']}/{grand['n_A_total']} = {pct_A:.2f}%")
    if grand['n_Bprime_total'] > 0:
        pct_B = 100.0 * grand['n_Bprime_ok'] / grand['n_Bprime_total']
        print(f"(B') within-one-s_i orbit-swap check: "
              f"{grand['n_Bprime_ok']}/{grand['n_Bprime_total']} = {pct_B:.2f}%")
    print(f"BGG signed-sum consistency at each bd: "
          f"{grand['bgg_signed_consistency_ok']}/{grand['bgg_signed_consistency_total']}")
    print()

    print("Per-s_i pure-orbit usage:")
    for si in sorted(grand['pure_use_by_si'].keys()):
        ct = grand['pure_use_by_si'][si]
        total = sum(ct.values())
        print(f"  s_{si}: {total} pure pairs")
    print()
    print("Per-s_i mixed-pair count:")
    for si in sorted(grand['mixed_distrib_by_si'].keys()):
        ct = grand['mixed_distrib_by_si'][si]
        total = sum(ct.values())
        n_distinct = len(ct)
        print(f"  s_{si}: {total} mixed pairs, {n_distinct} distinct distribution combos")
    print()
    if grand['mixed_examples']:
        print("Sample mixed pair examples:")
        for ex in grand['mixed_examples'][:3]:
            print(f"  lam={ex['lam']} mu={ex['mu']} s_{ex['si']}")
            print(f"    odd_pi = {ex['odd_pi']}")
            print(f"    even_pi = {ex['even_pi']}")
            print(f"    distribution = {ex['distribution']}")
            print(f"    pi_diff = {ex['pi_diff']}")
    print()


def main():
    print("Building W(F_4) and orbit data ...")
    t0 = time.time()
    weyl, _ = F4.build_weyl_F4()
    orbit_data = F4.compute_orbit_data()
    print(f"  done in {time.time() - t0:.1f}s. |W| = {len(weyl)}")

    pairs = dominant_integer_pairs_small()
    print(f"Test set: {len(pairs)} (lambda, mu) pairs.")
    print()
    grand = run_test(pairs, weyl, orbit_data, verbose=True)
    summarize(grand)
    return grand


if __name__ == "__main__":
    main()
