# Sanity check 2: the laws fail if we use Hamming-ball ~_r (NOT transitive!).
# Demonstrates WHY the chain filtration is the right design choice.

from itertools import product

n = 3
X = list(product([0,1], repeat=n))

def hamming(x, y):
    return sum(a != b for a, b in zip(x, y))

# Hamming-ball "equivalence" (not actually transitive)
def hamming_close(x, y, r):
    return hamming(x, y) <= r

# Transitive closure to get actual equivalence relation
def hamming_eqrel(r):
    # equivalence relation generated by hamming_close at radius r
    parent = {x: x for x in X}
    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x
    def union(x, y):
        parent[find(x)] = find(y)
    for x in X:
        for y in X:
            if hamming_close(x, y, r):
                union(x, y)
    classes = {}
    for x in X:
        classes.setdefault(find(x), []).append(x)
    return list(classes.values())

# For Hamming, the transitive closure of "distance ≤ r" for r >= 1 is the whole space.
print("Hamming-ball equivalence (with transitive closure):")
for r in range(n+1):
    cls = hamming_eqrel(r)
    print(f"  r={r}: {len(cls)} classes, sizes {sorted(len(c) for c in cls)}")

# CONCLUSION: Hamming-ball with r=1 already collapses to single class.
# So Hamming is not a useful filtration parameter. Chain projection IS.
