#!/usr/bin/env python3
"""
Minimal-cover droppability check (Day 78 stretch goal).

Background
==========
Task A (decisive_check.py) showed that for every interior i and every
alpha in {1, 2}, there exists an F-feasible piece pi with
        pi^{p_i} != T = e_{B_i} + alpha e_S
    AND e_{B_i} + alpha e_S in Im(pi).

Concretely the lifted-long witness W^{(i,alpha)} =
    {p_1 = e_{B_i}, l_2 = alpha * e_S, all else 0}
realizes the F2-ray p_1 + l_2 = T.

The OPEN question after Task A: when we DROP the carrier piece(s) from
the 53-piece registry cover and ADD W^{(i,alpha)} (or its lifted-short
sibling), does the modified piece-set STILL cover all the lattice
points the original cover covered?

If YES at some (i, alpha): the carrier is genuinely droppable, and the
3-clique on {p_i = 0, 1, 2} is broken in a working minimal cover.
If NO: the points LOST tell us exactly which OTHER lattice points the
carrier was supplying that the witness can't supply alone. That set of
LOSSES is the structural obstruction (Clio's section 9 Q2 mechanism).

Approach
========
1. Load the 53-piece n=6 registry in linkLHS=0 gauge.
2. Compute the joint-image semigroup of the full cover up to coord-sum K.
3. For each (i, alpha) in {(2,1),(2,2),(3,1),(3,2),(4,1),(4,2)}:
   (a) Identify carrier pieces (those whose p_i column == T).
   (b) Build the lifted-long witness W^{(i,alpha)}.
   (c) Compute joint image of modified cover (= original - carriers + W).
   (d) LOSSES := {points in original image NOT in modified image}.
   (e) Report:
       * |LOSSES|
       * Smallest losses (by coord-sum)
       * Whether T itself is still covered (sanity)

The losses are the structural witnesses to non-droppability.
"""
from __future__ import annotations
import json
import sys
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from bdi_n import (
    bdi_coords, bdi_idx, vec, add, scale, zero_piece, zero_vec,
    target_point, gen_set, all_cols, is_BDI, check_F,
    piece_to_human, semigroup_membership,
)
from task_B_replicate import load_n6_pieces_linkLHS_zero


N = 6


# =====================================================================
# Joint-image enumeration with sum bound
# =====================================================================
def joint_image_set(generators: list[tuple], max_sum: int) -> set:
    """Enumerate the semigroup generated by `generators` up to coord-sum
    max_sum. Returns set of tuples."""
    dim = 3 * N - 3
    Z = tuple([0] * dim)
    image = {Z}
    frontier = {Z}
    # Filter zero generators (they don't grow the semigroup).
    nonzero_gens = [g for g in generators if any(x > 0 for x in g)]
    while frontier:
        new_frontier = set()
        for v in frontier:
            for g in nonzero_gens:
                w = tuple(v[k] + g[k] for k in range(dim))
                if sum(w) <= max_sum and w not in image:
                    image.add(w)
                    new_frontier.add(w)
        frontier = new_frontier
    return image


def joint_generators(pieces_iter) -> list[tuple]:
    """Union of all 17 rays of each piece (deduplicated)."""
    gens = set()
    for piece in pieces_iter:
        for g in gen_set(N, piece):
            gens.add(g)
    return list(gens)


# =====================================================================
# Witness construction
# =====================================================================
def lifted_long_witness(i: int, alpha: int) -> dict:
    """W^{(i,alpha)} = {p_1 = e_{B_i}, l_2 = alpha e_S, rest 0}."""
    piece = zero_piece(N)
    piece["p1"] = vec(N, **{f"B{i}": 1})
    piece["l2"] = scale(alpha, vec(N, S=1))
    assert check_F(N, piece), \
        f"lifted-long witness not F-feasible at i={i}, alpha={alpha}"
    return piece


def lifted_short_witness(i: int, alpha: int) -> dict:
    """W^{(i,alpha)} = {p_1 = e_{B_i}, s_2 = alpha e_S, rest 0}."""
    piece = zero_piece(N)
    piece["p1"] = vec(N, **{f"B{i}": 1})
    piece["s2"] = scale(alpha, vec(N, S=1))
    assert check_F(N, piece), \
        f"lifted-short witness not F-feasible at i={i}, alpha={alpha}"
    return piece


# =====================================================================
# The check
# =====================================================================
def cover_droppability_check(pieces: dict, i: int, alpha: int,
                             witness_kind: str,
                             max_sum: int,
                             original_image: set) -> dict:
    """Run the droppability check at (i, alpha).

    Args:
      pieces: full registry (dict of name -> piece dict).
      i, alpha: target carrier (e_{B_i} + alpha e_S).
      witness_kind: "lifted_long" or "lifted_short".
      max_sum: coord-sum bound for joint-image enumeration.
      original_image: joint image of the full cover (precomputed).

    Returns dict with:
      'carrier_names': list of piece names whose p_i == T
      'modified_image_size': |modified joint image up to max_sum|
      'losses': sorted list of LOST points (in original, not in modified)
      'witness_F_feasible': bool
      'T_in_modified_image': bool (sanity: T should still be covered)
      'covers_all': bool (= len(losses) == 0)
    """
    T = target_point(N, i, alpha)

    # Carrier pieces.
    carriers = [name for name, p in pieces.items() if p[f"p{i}"] == T]

    # Build witness.
    if witness_kind == "lifted_long":
        W = lifted_long_witness(i, alpha)
    elif witness_kind == "lifted_short":
        W = lifted_short_witness(i, alpha)
    else:
        raise ValueError(witness_kind)

    # Modified cover.
    modified = [p for name, p in pieces.items() if name not in carriers]
    modified.append(W)

    # Joint generators + image of modified cover.
    mod_gens = joint_generators(modified)
    mod_image = joint_image_set(mod_gens, max_sum=max_sum)

    # Losses: points in original (truncated to <= max_sum) not in modified.
    # Both already truncated to <= max_sum.
    losses = original_image - mod_image
    losses_sorted = sorted(losses, key=lambda v: (sum(v), v))

    return {
        "i": i,
        "alpha": alpha,
        "witness_kind": witness_kind,
        "carrier_names": carriers,
        "n_carriers": len(carriers),
        "T_coords": {c: T[k] for k, c in enumerate(bdi_coords(N)) if T[k]},
        "max_sum": max_sum,
        "original_image_size": len(original_image),
        "modified_image_size": len(mod_image),
        "n_losses": len(losses),
        "smallest_losses": [
            {
                "vec": v,
                "coords": {c: v[k] for k, c in enumerate(bdi_coords(N)) if v[k]},
                "sum": sum(v),
            }
            for v in losses_sorted[:10]
        ],
        "covers_all": len(losses) == 0,
        "T_in_modified_image": T in mod_image,
    }


# =====================================================================
# Main
# =====================================================================
def main():
    print("=" * 76)
    print("Minimal-cover droppability check (Day 78 stretch)")
    print(f"  n = {N}")
    print("=" * 76)

    pieces = load_n6_pieces_linkLHS_zero()
    print(f"\nLoaded {len(pieces)} pieces from registry.")

    # F-check sanity.
    n_F = sum(1 for p in pieces.values() if check_F(N, p))
    print(f"F-feasible (linkLHS=0 gauge): {n_F}/{len(pieces)}")

    # Joint-image of full cover.
    max_sum = 6
    print(f"\nEnumerating joint image of full cover up to coord-sum {max_sum} ...")
    t0 = time.time()
    full_gens = joint_generators(pieces.values())
    print(f"  Total distinct rays across cover: {len(full_gens)}")
    full_image = joint_image_set(full_gens, max_sum=max_sum)
    el = time.time() - t0
    print(f"  |Im(cover) <= sum {max_sum}| = {len(full_image)}  ({el:.1f}s)")

    # Run check for each (i, alpha) and each witness kind.
    out = {
        "n": N,
        "max_sum": max_sum,
        "n_pieces": len(pieces),
        "n_distinct_rays": len(full_gens),
        "original_image_size": len(full_image),
        "checks": [],
    }
    for i in (2, 3, 4):
        for alpha in (1, 2):
            for witness_kind in ("lifted_long", "lifted_short"):
                print(f"\n--- i={i}, alpha={alpha}, witness={witness_kind} ---")
                t0 = time.time()
                res = cover_droppability_check(
                    pieces, i, alpha, witness_kind, max_sum, full_image
                )
                dt = time.time() - t0
                out["checks"].append(res)
                print(f"  carrier(s): {res['carrier_names']}")
                print(f"  modified image size: {res['modified_image_size']}  "
                      f"(orig {res['original_image_size']})")
                print(f"  losses: {res['n_losses']}  "
                      f"covers_all={res['covers_all']}  "
                      f"T still covered={res['T_in_modified_image']}  "
                      f"({dt:.1f}s)")
                if res["smallest_losses"]:
                    print(f"  smallest losses (up to 5):")
                    for L in res["smallest_losses"][:5]:
                        print(f"    sum={L['sum']}: {L['coords']}")

    # Summary table.
    print(f"\n{'=' * 76}")
    print("SUMMARY")
    print(f"{'=' * 76}")
    print(f"{'i':>3} {'alpha':>5} {'witness':>13} {'losses':>7} "
          f"{'covers_all':>10} {'T_covered':>9}")
    print("-" * 76)
    for r in out["checks"]:
        print(f"{r['i']:>3} {r['alpha']:>5} {r['witness_kind']:>13} "
              f"{r['n_losses']:>7} {str(r['covers_all']):>10} "
              f"{str(r['T_in_modified_image']):>9}")

    any_drops = any(r["covers_all"] for r in out["checks"])
    print(f"\nAny (i, alpha, witness) with FULLY DROPPABLE carrier? {any_drops}")

    # Save JSON.
    with open(HERE / "cover_droppability_results.json", "w") as f:
        json.dump(out, f, indent=2, default=str)
    print(f"\nWrote {HERE / 'cover_droppability_results.json'}")


if __name__ == "__main__":
    main()
