"""
Compute the change-of-basis matrix M: F -> F' between two LMNP-style
Verma bases of L(lambda) for sp_4, where:

    F  = { f_1^{a_4} f_2^{a_3} f_1^{a_2} f_2^{a_1} v_lambda } (Cao-Huang, w_0 = r_1 r_2 r_1 r_2)
    F' = { f_2^{a'_4} f_1^{a'_3} f_2^{a'_2} f_1^{a'_1} v_lambda } (w_0' = r_2 r_1 r_2 r_1)

Both are 40-element bases of L(omega_1 + 2 omega_2) = L(3 e_1 + 2 e_2) for sp_4 = C_2.

Strategy:
  1. PBW basis of U(n^-)(sp_4): {f_1^{c_1} f_{112}^{c_2} f_{12}^{c_3} f_2^{c_4}}
       where f_{12} = [f_1, f_2], f_{112} = [f_1, f_{12}].
     Commutation relations:
       [f_1, f_{112}] = 0  (Serre: ad(f_1)^3 f_2 = 0)
       [f_{112}, anything] = 0
       [f_{12}, f_1] = -f_{112}  (so f_{12} f_1 = f_1 f_{12} - f_{112})
       [f_{12}, f_2] = 0  (Serre: ad(f_2)^2 f_1 = 0)
       [f_2, f_1] = -f_{12}  (so f_2 f_1 = f_1 f_2 - f_{12})

  2. L(lambda) = U(n^-) / J where J = U(n^-) f_1^{m_1+1} + U(n^-) f_2^{m_2+1}
     (BGG: integral dominant lambda has max submodule of M(lambda) generated by
      the simple-root singular vectors).
     For lambda = omega_1 + 2 omega_2: m_1=1, m_2=2; J = U f_1^2 + U f_2^3.

  3. Build U(n^-)_mu in PBW basis for each weight mu = n_1 alpha_1 + n_2 alpha_2.
     Compute the subspace J_mu spanned by {w f_1^2 : w in U_{mu - 2 alpha_1}}
     and {w f_2^3 : w in U_{mu - 3 alpha_2}}. Then L(lambda)_mu = U_mu / J_mu.

  4. Expand each F-basis vector u_a and each F'-basis vector u'_a' in PBW
     basis. Each lives in U(n^-)_mu for appropriate mu.

  5. Solve M_{a', a} satisfying u'_{a'} = sum_a M_{a', a} u_a (mod J_mu),
     using linear algebra over Q.

  6. Analyze support, classify by net-move type Delta = a' - a (or similar).
"""

from fractions import Fraction
from collections import defaultdict
from itertools import product
from math import comb


# ---------------------------------------------------------------------
# PBW arithmetic
# ---------------------------------------------------------------------
# PBW monomial: tuple (c_1, c_2, c_3, c_4) = exponents of (f_1, f_112, f_12, f_2).
# PBW element: dict mapping tuple -> Fraction.

def zero():
    return {}


def clean(d):
    return {k: v for k, v in d.items() if v != 0}


def add(*elts):
    out = defaultdict(Fraction)
    for e in elts:
        for k, v in e.items():
            out[k] += v
    return clean(dict(out))


def scale(elt, c):
    if c == 0:
        return {}
    return {k: v * c for k, v in elt.items()}


def neg(elt):
    return {k: -v for k, v in elt.items()}


def mon(c1, c2, c3, c4, coef=1):
    if coef == 0:
        return {}
    return {(c1, c2, c3, c4): Fraction(coef)}


def left_mul_f1(elt):
    """Multiply elt by f_1 on the left.  f_1 . (f_1^{c1} f_112^{c2} f_12^{c3} f_2^{c4}) = (c1+1, c2, c3, c4)."""
    out = defaultdict(Fraction)
    for (c1, c2, c3, c4), v in elt.items():
        out[(c1 + 1, c2, c3, c4)] += v
    return clean(dict(out))


def left_mul_f2(elt):
    """Multiply elt by f_2 on the left.

    f_2 . f_1^{c1} f_112^{c2} f_12^{c3} f_2^{c4}
      = f_1^{c1} f_112^{c2} f_12^{c3} f_2^{c4+1}
        - c1 * f_1^{c1-1} f_112^{c2} f_12^{c3+1} f_2^{c4}
        + C(c1, 2) * f_1^{c1-2} f_112^{c2+1} f_12^{c3} f_2^{c4}.

    Derived from:
        [f_1, f_2] = f_12,  [f_1, f_12] = f_112,  [f_1, f_112] = 0,
        f_2 commutes with f_12 and f_112,
        f_12 commutes with f_112.
    Then f_2 f_1^c = f_1^c f_2 - c f_1^{c-1} f_12 + C(c,2) f_1^{c-2} f_112.
    """
    out = defaultdict(Fraction)
    for (c1, c2, c3, c4), v in elt.items():
        out[(c1, c2, c3, c4 + 1)] += v
        if c1 >= 1:
            out[(c1 - 1, c2, c3 + 1, c4)] += -c1 * v
        if c1 >= 2:
            out[(c1 - 2, c2 + 1, c3, c4)] += Fraction(comb(c1, 2)) * v
    return clean(dict(out))


def right_mul_pbw_mon(elt, e1, e2, e3, e4):
    """Multiply elt by the PBW monomial (e1, e2, e3, e4) on the RIGHT.

    This is needed for building generators of J = U f_1^2 + U f_2^3:
    we need {w * f_1^2} for arbitrary w, which is right-multiplication of w by f_1^2.

    Right-multiplication by f_1: an PBW monomial f_1^{c1} f_112^{c2} f_12^{c3} f_2^{c4}
    times f_1 on the right. We need to commute f_1 leftward past f_2^{c4}, then f_12^{c3},
    then f_112^{c2}, into f_1^{c1+...}.
    """
    # We compute by repeatedly applying right_mul_f1 / right_mul_f2.
    cur = elt
    for _ in range(e1):
        cur = right_mul_f1(cur)
    for _ in range(e2):
        cur = right_mul_f112(cur)
    for _ in range(e3):
        cur = right_mul_f12(cur)
    for _ in range(e4):
        cur = right_mul_f2(cur)
    return cur


def right_mul_f1(elt):
    """Multiply elt by f_1 on the right.

    f_1^{c1} f_112^{c2} f_12^{c3} f_2^{c4} . f_1
    = f_1^{c1} f_112^{c2} f_12^{c3} (f_2^{c4} f_1).
    We need f_2^{c4} f_1 in PBW form: use f_2^k f_1 iteratively.

    f_2 f_1 = f_1 f_2 - f_12
    f_2^2 f_1 = f_2 (f_2 f_1) = f_2 (f_1 f_2 - f_12) = (f_2 f_1) f_2 - f_2 f_12
              = (f_1 f_2 - f_12) f_2 - f_12 f_2
              = f_1 f_2^2 - 2 f_12 f_2
    f_2^k f_1 = f_1 f_2^k - k f_12 f_2^{k-1}   (general, since [f_2, f_12]=0 simplifies)

    Then  (f_12^{c3}) . (f_1 f_2^k - k f_12 f_2^{k-1})
        = f_12^{c3} f_1 f_2^k - k f_12^{c3+1} f_2^{k-1}.
    Use f_12^{c3} f_1 in PBW:
        f_12 f_1 = f_1 f_12 - f_112
        f_12^j f_1 = f_1 f_12^j - j f_112 f_12^{j-1}  (since [f_1, f_112]=0)
    """
    out = defaultdict(Fraction)
    for (c1, c2, c3, c4), v in elt.items():
        # Step 1:  f_2^{c4} . f_1 = f_1 f_2^{c4} - c4 f_12 f_2^{c4 - 1}
        # (uses [f_2, f_12] = 0)
        # so f_12^{c3} f_2^{c4} f_1 = f_12^{c3} (f_1 f_2^{c4} - c4 f_12 f_2^{c4-1})
        # Step 2: simplify f_12^{c3} f_1 = f_1 f_12^{c3} - c3 f_112 f_12^{c3-1}
        #
        # Two terms after step 1:
        # term A: f_1^{c1} f_112^{c2} f_12^{c3} f_1 f_2^{c4}
        #       = f_1^{c1} f_112^{c2} (f_1 f_12^{c3} - c3 f_112 f_12^{c3-1}) f_2^{c4}
        #       = f_1^{c1+1} f_112^{c2} f_12^{c3} f_2^{c4}    -- since f_1 f_112^{c2} = f_112^{c2} f_1
        #         - c3 f_1^{c1} f_112^{c2+1} f_12^{c3-1} f_2^{c4}
        # term B: -c4 * f_1^{c1} f_112^{c2} f_12^{c3+1} f_2^{c4-1}
        out[(c1 + 1, c2, c3, c4)] += v
        if c3 >= 1:
            out[(c1, c2 + 1, c3 - 1, c4)] += -c3 * v
        if c4 >= 1:
            out[(c1, c2, c3 + 1, c4 - 1)] += -c4 * v
    return clean(dict(out))


def right_mul_f2(elt):
    """Multiply elt by f_2 on the right.  Since f_2 commutes with f_12, f_112, and itself,
    this just increments c4."""
    out = defaultdict(Fraction)
    for (c1, c2, c3, c4), v in elt.items():
        out[(c1, c2, c3, c4 + 1)] += v
    return clean(dict(out))


def right_mul_f12(elt):
    """Right-mult by f_12.

    f_1^{c1} f_112^{c2} f_12^{c3} f_2^{c4} . f_12
    = f_1^{c1} f_112^{c2} f_12^{c3} f_12 f_2^{c4}    (f_2 and f_12 commute)
    = f_1^{c1} f_112^{c2} f_12^{c3+1} f_2^{c4}.
    """
    out = defaultdict(Fraction)
    for (c1, c2, c3, c4), v in elt.items():
        out[(c1, c2, c3 + 1, c4)] += v
    return clean(dict(out))


def right_mul_f112(elt):
    """Right-mult by f_112.  f_112 commutes with everything, so just increment c2."""
    out = defaultdict(Fraction)
    for (c1, c2, c3, c4), v in elt.items():
        out[(c1, c2 + 1, c3, c4)] += v
    return clean(dict(out))


# ---------------------------------------------------------------------
# Sanity tests for arithmetic
# ---------------------------------------------------------------------

def test_arithmetic():
    # f_2 f_1 = f_1 f_2 - f_12
    a = mon(0, 0, 0, 0)
    a = left_mul_f1(a)            # f_1
    a = left_mul_f2(a)            # f_2 f_1
    expected = add(mon(1, 0, 0, 1), mon(0, 0, 1, 0, coef=-1))
    assert a == expected, (a, expected)

    # f_2 f_1^2 = f_1^2 f_2 - 2 f_1 f_12 + f_112
    a = mon(0, 0, 0, 0)
    a = left_mul_f1(a)
    a = left_mul_f1(a)
    a = left_mul_f2(a)
    expected = add(mon(2, 0, 0, 1), mon(1, 0, 1, 0, coef=-2), mon(0, 1, 0, 0, coef=1))
    assert a == expected, (a, expected)

    # f_2 f_1^3 = f_1^3 f_2 - 3 f_1^2 f_12 + 3 f_1 f_112
    a = mon(0, 0, 0, 0)
    a = left_mul_f1(a)
    a = left_mul_f1(a)
    a = left_mul_f1(a)
    a = left_mul_f2(a)
    expected = add(mon(3, 0, 0, 1), mon(2, 0, 1, 0, coef=-3), mon(1, 1, 0, 0, coef=3))
    assert a == expected, (a, expected)

    # right_mul_f1(f_2) should give f_2 f_1 = f_1 f_2 - f_12
    a = mon(0, 0, 0, 1)
    a = right_mul_f1(a)
    expected = add(mon(1, 0, 0, 1), mon(0, 0, 1, 0, coef=-1))
    assert a == expected, (a, expected)

    # right_mul_f1 of f_12 should give f_12 f_1 = f_1 f_12 - f_112
    a = mon(0, 0, 1, 0)
    a = right_mul_f1(a)
    expected = add(mon(1, 0, 1, 0), mon(0, 1, 0, 0, coef=-1))
    assert a == expected, (a, expected)

    # f_2 f_12 should equal f_12 f_2 (commute)
    a1 = mon(0, 0, 1, 0)
    a1 = left_mul_f2(a1)
    a2 = mon(0, 0, 0, 1)
    a2 = right_mul_f12(a2)
    assert a1 == a2, (a1, a2)

    print("Arithmetic tests passed.")


# ---------------------------------------------------------------------
# Build F = LMNP basis for w_0 = r_1 r_2 r_1 r_2 at lambda = omega_1 + 2 omega_2
# ---------------------------------------------------------------------

def build_u_a(a):
    """u_a = f_1^{a_4} f_2^{a_3} f_1^{a_2} f_2^{a_1} (in PBW form, applied to v_lambda).

    a = (a_1, a_2, a_3, a_4).
    """
    a1, a2, a3, a4 = a
    cur = mon(0, 0, 0, 0)
    # Apply f_2^{a_1} on the left (innermost)
    for _ in range(a1):
        cur = left_mul_f2(cur)
    # Then f_1^{a_2}
    for _ in range(a2):
        cur = left_mul_f1(cur)
    # Then f_2^{a_3}
    for _ in range(a3):
        cur = left_mul_f2(cur)
    # Then f_1^{a_4} (outermost)
    for _ in range(a4):
        cur = left_mul_f1(cur)
    return cur


def build_u_a_prime(a):
    """u'_{a'} = f_2^{a'_4} f_1^{a'_3} f_2^{a'_2} f_1^{a'_1}."""
    a1, a2, a3, a4 = a
    cur = mon(0, 0, 0, 0)
    # f_1^{a'_1} on the right-most, applied first
    for _ in range(a1):
        cur = left_mul_f1(cur)
    # f_2^{a'_2}
    for _ in range(a2):
        cur = left_mul_f2(cur)
    # f_1^{a'_3}
    for _ in range(a3):
        cur = left_mul_f1(cur)
    # f_2^{a'_4}
    for _ in range(a4):
        cur = left_mul_f2(cur)
    return cur


# ---------------------------------------------------------------------
# Cao-Huang admissibility for F (from existing code)
# ---------------------------------------------------------------------

def admissible_F(m1, m2):
    """Cao-Huang admissibility for w_0 = r_1 r_2 r_1 r_2."""
    out = []
    for a1 in range(m2 + 1):
        for a2 in range(m1 + 2 * a1 + 1):
            top_a3 = min((a2 + m1) // 2, a2)
            for a3 in range(top_a3 + 1):
                for a4 in range(min(m1, a3) + 1):
                    out.append((a1, a2, a3, a4))
    return out


# ---------------------------------------------------------------------
# Weight of a tuple
# ---------------------------------------------------------------------

def weight_F(a, m1, m2):
    """Weight of u_a = f_1^{a4} f_2^{a3} f_1^{a2} f_2^{a1} v_lambda is
    lambda - (a_2 + a_4) alpha_1 - (a_1 + a_3) alpha_2.
    Return (n1, n2) where lambda - mu = n1 alpha_1 + n2 alpha_2."""
    a1, a2, a3, a4 = a
    return (a2 + a4, a1 + a3)


def weight_Fp(a, m1, m2):
    """Weight of u'_a' = f_2^{a'4} f_1^{a'3} f_2^{a'2} f_1^{a'1} v_lambda is
    lambda - (a'_1 + a'_3) alpha_1 - (a'_2 + a'_4) alpha_2.
    """
    a1, a2, a3, a4 = a
    return (a1 + a3, a2 + a4)


# ---------------------------------------------------------------------
# PBW dimension at weight mu = (n1, n2) (in alpha_1, alpha_2 coords)
# A PBW monomial (c1, c2, c3, c4) has weight c1*alpha_1 + c2*(2 alpha_1 + alpha_2)
#   + c3*(alpha_1 + alpha_2) + c4*alpha_2 = (c1 + 2c2 + c3) alpha_1 + (c2 + c3 + c4) alpha_2.
# So mu = (n1, n2) means c1 + 2c2 + c3 = n1 AND c2 + c3 + c4 = n2.
# ---------------------------------------------------------------------

def pbw_mons_at_weight(n1, n2):
    """All (c1, c2, c3, c4) with c_i >= 0 such that c1+2c2+c3=n1, c2+c3+c4=n2."""
    out = []
    for c2 in range(min(n1 // 2, n2) + 1):
        for c3 in range(min(n1 - 2 * c2, n2 - c2) + 1):
            c1 = n1 - 2 * c2 - c3
            c4 = n2 - c2 - c3
            if c1 >= 0 and c4 >= 0:
                out.append((c1, c2, c3, c4))
    return out


# ---------------------------------------------------------------------
# Build kernel J = U f_1^{m1+1} + U f_2^{m2+1}
# ---------------------------------------------------------------------

def kernel_basis_at_weight(n1, n2, m1, m2):
    """Generators of J_mu where mu = n1 alpha_1 + n2 alpha_2, in PBW expansion.

    J = U(n-) f_1^{m1+1} + U(n-) f_2^{m2+1}.
    J_mu is spanned by:
      { w * f_1^{m1+1} : w PBW monomial of weight (n1 - (m1+1), n2) }
      { w * f_2^{m2+1} : w PBW monomial of weight (n1, n2 - (m2+1)) }

    Returns list of PBW elements (dicts).
    """
    gens = []
    # w * f_1^{m1+1}: w of weight (n1 - (m1+1), n2)
    if n1 >= m1 + 1:
        for w_mon in pbw_mons_at_weight(n1 - (m1 + 1), n2):
            w_elt = mon(*w_mon)
            res = right_mul_pbw_mon(w_elt, m1 + 1, 0, 0, 0)
            gens.append(res)
    # w * f_2^{m2+1}: w of weight (n1, n2 - (m2+1))
    if n2 >= m2 + 1:
        for w_mon in pbw_mons_at_weight(n1, n2 - (m2 + 1)):
            w_elt = mon(*w_mon)
            res = right_mul_pbw_mon(w_elt, 0, 0, 0, m2 + 1)
            gens.append(res)
    return gens


# ---------------------------------------------------------------------
# Convert PBW element (dict) to a vector indexed by ordered PBW monomial list
# ---------------------------------------------------------------------

def pbw_to_vec(elt, mon_list):
    idx = {m: i for i, m in enumerate(mon_list)}
    v = [Fraction(0)] * len(mon_list)
    for k, val in elt.items():
        v[idx[k]] = val
    return v


# ---------------------------------------------------------------------
# Linear algebra: row-reduce over Q to find J_mu, and solve change-of-basis.
# ---------------------------------------------------------------------

def rref(matrix):
    """In-place reduced row echelon form over Q. Modifies matrix.
    Returns the list of pivot column indices."""
    if not matrix:
        return []
    n_rows = len(matrix)
    n_cols = len(matrix[0])
    pivots = []
    r = 0
    for c in range(n_cols):
        if r >= n_rows:
            break
        # find pivot
        pivot_row = None
        for i in range(r, n_rows):
            if matrix[i][c] != 0:
                pivot_row = i
                break
        if pivot_row is None:
            continue
        matrix[r], matrix[pivot_row] = matrix[pivot_row], matrix[r]
        # scale
        pv = matrix[r][c]
        for j in range(n_cols):
            matrix[r][j] /= pv
        # eliminate
        for i in range(n_rows):
            if i != r and matrix[i][c] != 0:
                factor = matrix[i][c]
                for j in range(n_cols):
                    matrix[i][j] -= factor * matrix[r][j]
        pivots.append(c)
        r += 1
    return pivots


def solve_quotient(target_vec, basis_vecs, J_vecs, n_cols):
    """Find coefficients (c_1, ..., c_k) such that
        target_vec = sum_i c_i * basis_vecs[i] + j  for some j in span(J_vecs).

    We assume basis_vecs together with J_vecs form a basis of the span of {basis_vecs} + J.
    (basis_vecs are the u_a's at weight mu; J_vecs are generators of J_mu.)

    Build matrix [J_vecs | basis_vecs | -target_vec] and solve.
    Equivalently: find c with sum c_i basis_vecs[i] - target_vec in span(J_vecs).

    We do: set up A = [J | basis_vecs] (cols = J gens + basis gens) and solve
    A x = target.  The c coefficients are the entries of x corresponding to basis_vecs.
    """
    n_J = len(J_vecs)
    n_basis = len(basis_vecs)
    n_total = n_J + n_basis
    # Build augmented matrix: each row corresponds to a PBW monomial coordinate.
    # We have n_cols rows.
    # Augmented: columns = J cols + basis cols + target col (rhs)
    mat = []
    for r in range(n_cols):
        row = []
        for jv in J_vecs:
            row.append(jv[r])
        for bv in basis_vecs:
            row.append(bv[r])
        row.append(target_vec[r])
        mat.append(row)
    # row-reduce
    rref(mat)
    # Read off the solution: we want x with A x = target.
    # If the system is consistent, the solution might not be unique (kernel space).
    # We want the basis-coefficients c.

    # Easier: solve via a different route.
    # Find any particular solution.
    # After RREF, rows with all-zero LHS and nonzero RHS => inconsistent.
    # Otherwise pick the basis_vec coefficients from rows whose pivot is in the basis_vec block.
    # If a basis_vec column has no pivot (i.e., is in span of J + previous basis cols),
    # we have non-uniqueness => the target had a free choice.

    # Better: I'll just solve the system "find x with A x = target" by setting up A
    # and doing Gauss-Jordan.

    # Set free vars to 0 — but free vars exist iff system is rank-deficient or has
    # kernel.  For our case (basis_vecs are a basis mod J, J has its own basis after
    # row-reduction), I expect the J columns to be linearly independent, and adding
    # basis_vecs gives full rank — so unique solution.

    # Let me redo: do RREF on [A | target] and read off pivots.
    # If row i has pivot in column j < n_total and nonzero rhs (mat[i][-1]), then x_j = mat[i][-1].
    # If row i has all-zero LHS and nonzero rhs, INCONSISTENT.

    c = [Fraction(0)] * n_basis
    pivots_set = {}
    for row in mat:
        # Find first nonzero LHS column
        pivot = None
        for j in range(n_total):
            if row[j] != 0:
                pivot = j
                break
        if pivot is None:
            if row[-1] != 0:
                raise ValueError("Inconsistent system: target not in span(J + basis)")
            continue
        pivots_set[pivot] = row[-1]
    # The c_i = pivots_set.get(n_J + i, 0). Free basis vars => set to 0 (then
    # adjust J vars to absorb). We just read the unique part.
    for i in range(n_basis):
        c[i] = pivots_set.get(n_J + i, Fraction(0))
    return c


# ---------------------------------------------------------------------
# Main: compute change-of-basis matrix M: F -> F'
# ---------------------------------------------------------------------

def compute_braid_transition(m1, m2, F_admissible, Fp_admissible):
    """Compute M[(a, a_prime)] = coefficient of u_a in expansion of u'_{a_prime}
    in terms of {u_a}, computed in L(lambda).
    """
    # Group F by weight
    F_by_wt = defaultdict(list)
    for a in F_admissible:
        F_by_wt[weight_F(a, m1, m2)].append(a)

    # Group F' by weight
    Fp_by_wt = defaultdict(list)
    for ap in Fp_admissible:
        Fp_by_wt[weight_Fp(ap, m1, m2)].append(ap)

    # Check weights match in dimension
    for wt in F_by_wt:
        if len(F_by_wt[wt]) != len(Fp_by_wt.get(wt, [])):
            print(f"  WARNING: weight {wt} has {len(F_by_wt[wt])} F-vecs but "
                  f"{len(Fp_by_wt.get(wt, []))} F'-vecs")

    M = {}  # M[(a_prime, a)] = coef
    # For each weight, expand u'_{a_prime} in {u_a}
    for wt, ap_list in sorted(Fp_by_wt.items()):
        n1, n2 = wt
        # PBW basis at this weight
        pbw_mons = pbw_mons_at_weight(n1, n2)
        # Generators of J_mu
        J_gens = kernel_basis_at_weight(n1, n2, m1, m2)
        # F-basis vectors at this weight (in PBW expansion)
        a_list = F_by_wt[wt]
        basis_elts = [build_u_a(a) for a in a_list]
        # Convert to vectors
        basis_vecs = [pbw_to_vec(b, pbw_mons) for b in basis_elts]
        J_vecs = [pbw_to_vec(j, pbw_mons) for j in J_gens]
        # For each F'-basis vector at this weight, expand
        for ap in ap_list:
            target_elt = build_u_a_prime(ap)
            target_vec = pbw_to_vec(target_elt, pbw_mons)
            coefs = solve_quotient(target_vec, basis_vecs, J_vecs, len(pbw_mons))
            for i, a in enumerate(a_list):
                if coefs[i] != 0:
                    M[(ap, a)] = coefs[i]
    return M


# ---------------------------------------------------------------------
# F' admissibility: determine by computing which a' are linearly independent
# ---------------------------------------------------------------------

def find_Fp_admissible(m1, m2, max_search=None):
    """Find a maximal set of a' = (a'1, a'2, a'3, a'4) such that {u'_a' v_lambda}
    are linearly independent in L(lambda).

    Strategy: enumerate weights mu = n1 alpha_1 + n2 alpha_2 in the support of L(lambda),
    and for each weight, find a maximal linearly independent set of u'_a' modulo J_mu.

    We bound the search: a'1 + a'3 = n1 <= max n1 in support, a'2 + a'4 = n2 <= max n2.
    """
    # First get the F-weight support to know which weights exist
    F_adm = admissible_F(m1, m2)
    F_by_wt = defaultdict(list)
    for a in F_adm:
        F_by_wt[weight_F(a, m1, m2)].append(a)

    Fp_adm = []
    for wt, a_list in sorted(F_by_wt.items()):
        n1, n2 = wt
        # Generate all candidate a' with weight (n1, n2):
        # n1 = a'1 + a'3, n2 = a'2 + a'4
        candidates = []
        for ap1 in range(n1 + 1):
            ap3 = n1 - ap1
            for ap2 in range(n2 + 1):
                ap4 = n2 - ap2
                candidates.append((ap1, ap2, ap3, ap4))

        # Build PBW expansions and select a maximal independent set mod J
        pbw_mons = pbw_mons_at_weight(n1, n2)
        J_gens = kernel_basis_at_weight(n1, n2, m1, m2)
        J_vecs = [pbw_to_vec(j, pbw_mons) for j in J_gens]
        # Row-reduce J_vecs (as rows) to get a basis of J_mu
        J_mat = [list(r) for r in J_vecs]
        if J_mat:
            rref(J_mat)
            J_basis = [r for r in J_mat if any(x != 0 for x in r)]
        else:
            J_basis = []

        # Now for each candidate, check if it's linearly independent of {already picked} mod J.
        picked = []
        running_mat = [list(r) for r in J_basis]
        for ap in candidates:
            target_elt = build_u_a_prime(ap)
            target_vec = pbw_to_vec(target_elt, pbw_mons)
            # Try to extend the running_mat with target_vec; check if it adds rank.
            test_mat = [list(r) for r in running_mat] + [list(target_vec)]
            rref(test_mat)
            new_rank = sum(1 for r in test_mat if any(x != 0 for x in r))
            if new_rank > len(running_mat):
                # adds rank => linearly independent of current picks mod J
                picked.append(ap)
                running_mat = [r for r in test_mat if any(x != 0 for x in r)]
            if len(picked) == len(a_list):
                break
        if len(picked) < len(a_list):
            print(f"  WARNING: weight {wt} expected {len(a_list)} F'-vecs but only "
                  f"found {len(picked)} candidates linearly independent. Increasing search.")
            # Try more candidates if needed (shouldn't happen for compact weights)
        Fp_adm.extend(picked)
    return Fp_adm


# ---------------------------------------------------------------------
# Main runner
# ---------------------------------------------------------------------

def main():
    test_arithmetic()

    m1, m2 = 1, 2  # lambda = omega_1 + 2 omega_2 = 3 e_1 + 2 e_2, dim L(lambda) = 40

    F_adm = admissible_F(m1, m2)
    print(f"\n|F| = {len(F_adm)} (expected 40)")

    # Find F' admissibility
    print(f"\nFinding F'-admissibility...")
    Fp_adm = find_Fp_admissible(m1, m2)
    print(f"|F'| = {len(Fp_adm)} (expected 40)")

    # Compute change-of-basis matrix M: F -> F'
    print(f"\nComputing change-of-basis matrix M: F -> F' ...")
    M = compute_braid_transition(m1, m2, F_adm, Fp_adm)
    print(f"Number of nonzero entries in M: {len(M)}")

    # Print support
    print(f"\nSupport of M (pairs (a', a) with M[a', a] != 0):")
    by_wt = defaultdict(list)
    for (ap, a), val in M.items():
        wt = weight_F(a, m1, m2)
        by_wt[wt].append((ap, a, val))
    for wt in sorted(by_wt):
        print(f"\n  weight (n1={wt[0]}, n2={wt[1]}):")
        for ap, a, val in sorted(by_wt[wt]):
            tag = " DIAGONAL" if ap == a else ""
            print(f"    a' = {ap}  <- a = {a}  : {val}{tag}")

    # Save M to file
    import json
    out = {
        'F_admissible': [list(a) for a in F_adm],
        'Fp_admissible': [list(a) for a in Fp_adm],
        'M_entries': [{'a_prime': list(ap), 'a': list(a), 'coef': str(val)}
                      for (ap, a), val in M.items()]
    }
    import os
    path = os.path.join(os.path.dirname(__file__), 'M_matrix.json')
    with open(path, 'w') as f:
        json.dump(out, f, indent=2)
    print(f"\nSaved to {path}")


if __name__ == '__main__':
    main()
